### ISSUE TITLE
Discord Music bot

### ISSUE THREAD

**Issue by anushkrishnav** [anushkrishnav/PyAutomate#12]
Make a Simple music Bot for Discord Server

**Comment by kamil200** [comment]
i would love contribute in this feature, please assign me

**Comment by kamil200** [comment]
sorry to inform you that i am unable to add this feature . i think it is overwhelming for me.
i am unassigning myself.

**Comment by taroken6** [comment]
Hello, can I take over this issue?

**Comment by anushkrishnav** [comment]
@taroken6 Go ahead

**Comment by Xx-Ashutosh-xX** [comment]
Hi!, I am also learning about making Discord bots, can I also contribute to this?

**Comment by anushkrishnav** [comment]
> Hi!, I am also learning about making Discord bots, can I also contribute to this?
You can make a Meme bot  or tech news bot Imagination is the limit

**Comment by Xx-Ashutosh-xX** [comment]
> > You can make a Meme bot  or tech news bot Imagination is the limit
Oh actually I already made a simple music bot, anyways I will try to add the meme feature too

**Comment by anushkrishnav** [comment]
Closing this issue . Thank you Please leave a star :)
