### ISSUE TITLE
Python Linter

### ISSUE THREAD

**Issue by anushkrishnav** [anushkrishnav/PyAutomate#14]
Add a GitHub action to Lint PR

**Comment by cmccandless** [comment]
Hi @anushkrishnav, I think I can help with this. To clarify, you just want to run flake8 on the Python source for pull requests, yes?

I noticed [flaske8.yml](https://github.com/anushkrishnav/PyAutomate/blob/master/.github/workflows/flaske8.yml), which appears to be attempting to do this, but is configured incorrectly. Would you like me to edit that workflow, or to create a separate one?

**Comment by anushkrishnav** [comment]
> Hi @anushkrishnav, I think I can help with this. To clarify, you just want to run flake8 on the Python source for pull requests, yes?
> 
> I noticed [flaske8.yml](https://github.com/anushkrishnav/PyAutomate/blob/master/.github/workflows/flaske8.yml), which appears to be attempting to do this, but is configured incorrectly. Would you like me to edit that workflow, or to create a separate one?

If you can configure it and fix the issue would be great, Please work on a sep branch and issue a PR. Also, if you can add an action for Code Coverage. Would be helpful
