### ISSUE TITLE
MP4 to MP3

### ISSUE THREAD

**Issue by anushkrishnav** [anushkrishnav/PyAutomate#21]
Why use the tool on the internet and risk getting a virus when you can use your own code to do the same.

**Comment by SethWalkeroo** [comment]
Hello, I would like to be assigned this issue.

**Comment by anushkrishnav** [comment]
Go ahead @SethWalkeroo

**Comment by buabaj** [comment]
is this taken?

**Comment by anushkrishnav** [comment]
@buabaj Yes if you want you can work on converting mp4 to gif

**Comment by buabaj** [comment]
awesome! on it.

**Comment by anushkrishnav** [comment]
> awesome! on it.

Open an issue and work on it while submitting the PR reference it . [Check the guidelines](https://github.com/anushkrishnav/PyAutomate#contributing-guidelines)
