### ISSUE TITLE
PDF to Audio Book

### ISSUE THREAD

**Issue by rkgeekoftheweek** [anushkrishnav/PyAutomate#33]
If you are lazy to read a pdf book , lets listen it from simple few lines of python code.

**Comment by rkgeekoftheweek** [comment]
@anushkrishnav , Please assign this to me.

**Comment by kubercodes** [comment]
Hey @anushkrishnav I am interested in doing this .Please assign this to me .

**Comment by Mremmalex** [comment]
Hello @anushkrishnav I have interest in working on this project, have a local prototype already

**Comment by anushkrishnav** [comment]
@kubercodes  and @Mremmalex    @rkgeekoftheweek  opened this issue so assigning this issue to him/her. If you have any other awesome scripts Feel free to open an issue and work on a PR . Have a great day
