### ISSUE TITLE
adding voice control for whatsapp

### ISSUE THREAD

**Issue by Nish251103** [anushkrishnav/PyAutomate#34]
This would be a added feature in WhatsApp bot Where in the user could speak up the message which is to be sent to the target.

**Comment by anushkrishnav** [comment]
Please provide details on what you are planning to work /improve

**Comment by Nish251103** [comment]
Done.
Kindly have a look

**Comment by Nish251103** [comment]
> Done with description
> Kindly have a look

**Comment by anushkrishnav** [comment]
> Done with description.
> Kindly have a look

Please issue a PR

**Comment by Nish251103** [comment]
Okay will do that

**Comment by Nish251103** [comment]
Done the task #47

**Comment by anushkrishnav** [comment]
PLease add a readme file to explain the code and how to use it thanks . Please leave a like :)

**Comment by Nish251103** [comment]
The usage is same as already mentioned in README Just it has additional requirements which I have already attached and Yeah I will add its functionality into README
Thank you

**Comment by anushkrishnav** [comment]
Awesome

**Comment by Nish251103** [comment]
Done the required stuff. Have a look and kindly suggest changes if any.
Thank you

**Comment by anushkrishnav** [comment]
waiting for the bot to scan it .fix issues if any

**Comment by Nish251103** [comment]
Okay

**Comment by Nish251103** [comment]
The program is working fine in my machine so I guess no issues.

**Comment by anushkrishnav** [comment]
Awesome . Will review once I get some time

**Comment by Nish251103** [comment]
Sure.
By that time can you add a Hacktoberfest accepted label on the PR if you feel its legit

**Comment by Nish251103** [comment]
Sure, No hurry
Thank you
