### ISSUE TITLE
Issue Notifier Discord Bot

### ISSUE THREAD

**Issue by anushkrishnav** [anushkrishnav/PyAutomate#38]
Discord Bot to notify the DIscord Community about an open issue or a PR. Please explain how you did it and the resource you used or referred. And a brief guide on how to use it. Feel free to drop me a message if you need help :)

**Comment by Andreybest** [comment]
Hello! I've got a good knowlage in creating discord bots, but in JS (discord.js), but I can try writing one in python, is that good? Can I have this issue?

**Comment by anushkrishnav** [comment]
Yesh please go ahead and give it a try .Let me know If you need some help :) Have a great day

**Comment by Andreybest** [comment]
Hello, I've added solution files for this task. Let me know if I missing something!

**Comment by anushkrishnav** [comment]
> Hello, I've added solution files for this task. Let me know if I missing something!

I have merged the PR
